require 'jar_dependencies'
JBUNDLER_LOCAL_REPO = Jars.home
JBUNDLER_JRUBY_CLASSPATH = []
JBUNDLER_JRUBY_CLASSPATH.freeze
JBUNDLER_TEST_CLASSPATH = []
JBUNDLER_TEST_CLASSPATH.freeze
JBUNDLER_CLASSPATH = []
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/mybatis/mybatis/3.3.0/mybatis-3.3.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/log4j/log4j/1.2.17/log4j-1.2.17.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/aopalliance/aopalliance/1.0/aopalliance-1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-svggen/1.7/batik-svggen-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-modeler/5.22.0/activiti-modeler-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/security/spring-security-core/3.2.3.RELEASE/spring-security-core-3.2.3.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/xmlgraphics-commons/1.2/xmlgraphics-commons-1.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-util/1.7/batik-util-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-gvt/1.7/batik-gvt-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/avalon/framework/avalon-framework-impl/4.3.1/avalon-framework-impl-4.3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-parser/1.7/batik-parser-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-script/1.7/batik-script-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-beans/4.1.5.RELEASE/spring-beans-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-bridge/1.7/batik-bridge-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/avalon/framework/avalon-framework-api/4.3.1/avalon-framework-api-4.3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-common-rest/5.22.0/activiti-common-rest-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-svg-dom/1.7/batik-svg-dom-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-aop/4.1.5.RELEASE/spring-aop-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-js/1.7/batik-js-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-expression/4.1.5.RELEASE/spring-expression-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/security/spring-security-config/3.2.3.RELEASE/spring-security-config-3.2.3.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/math/geom2d/javaGeom/0.11.1/javaGeom-0.11.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/fop/0.94/fop-0.94.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-dom/1.7/batik-dom-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-json-converter/5.22.0/activiti-json-converter-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-image-generator/5.22.0/activiti-image-generator-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/h2database/h2/1.4.193/h2-1.4.193.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-codec/1.7/batik-codec-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-process-validation/5.22.0/activiti-process-validation-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-engine/5.22.0/activiti-engine-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-webmvc/4.1.5.RELEASE/spring-webmvc-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-css/1.7/batik-css-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-context/4.1.5.RELEASE/spring-context-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-core/4.1.5.RELEASE/spring-core-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-awt-util/1.7/batik-awt-util-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-xml/1.7/batik-xml-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-bpmn-model/5.22.0/activiti-bpmn-model-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-web/4.1.5.RELEASE/spring-web-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/security/spring-security-crypto/3.2.3.RELEASE/spring-security-crypto-3.2.3.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/activation/activation/1.1.1/activation-1.1.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/commons/commons-email/1.4/commons-email-1.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/sun/mail/javax.mail/1.5.2/javax.mail-1.5.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/spring-tx/4.1.5.RELEASE/spring-tx-4.1.5.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/jline/jline/2.11/jline-2.11.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/activiti/activiti-bpmn-converter/5.22.0/activiti-bpmn-converter-5.22.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-transcoder/1.7/batik-transcoder-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/joda-time/joda-time/2.6/joda-time-2.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-io/commons-io/1.1/commons-io-1.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-anim/1.7/batik-anim-1.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/springframework/security/spring-security-web/3.2.3.RELEASE/spring-security-web-3.2.3.RELEASE.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/xmlgraphics/batik-ext/1.7/batik-ext-1.7.jar')
JBUNDLER_CLASSPATH.freeze
